
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ProductVideo` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ProductVideo
 * 
 */
export type ProductVideoModel = runtime.Types.Result.DefaultSelection<Prisma.$ProductVideoPayload>

export type AggregateProductVideo = {
  _count: ProductVideoCountAggregateOutputType | null
  _avg: ProductVideoAvgAggregateOutputType | null
  _sum: ProductVideoSumAggregateOutputType | null
  _min: ProductVideoMinAggregateOutputType | null
  _max: ProductVideoMaxAggregateOutputType | null
}

export type ProductVideoAvgAggregateOutputType = {
  progressPercent: number | null
}

export type ProductVideoSumAggregateOutputType = {
  progressPercent: number | null
}

export type ProductVideoMinAggregateOutputType = {
  id: string | null
  productsHash: string | null
  videoKey: string | null
  videoId: string | null
  triggerRunId: string | null
  workflowStatus: $Enums.ProductVideoWorkflowStatus | null
  progressPercent: number | null
  progressLabel: string | null
  errorMessage: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ProductVideoMaxAggregateOutputType = {
  id: string | null
  productsHash: string | null
  videoKey: string | null
  videoId: string | null
  triggerRunId: string | null
  workflowStatus: $Enums.ProductVideoWorkflowStatus | null
  progressPercent: number | null
  progressLabel: string | null
  errorMessage: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ProductVideoCountAggregateOutputType = {
  id: number
  productsHash: number
  videoKey: number
  videoId: number
  triggerRunId: number
  workflowStatus: number
  progressPercent: number
  progressLabel: number
  errorMessage: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ProductVideoAvgAggregateInputType = {
  progressPercent?: true
}

export type ProductVideoSumAggregateInputType = {
  progressPercent?: true
}

export type ProductVideoMinAggregateInputType = {
  id?: true
  productsHash?: true
  videoKey?: true
  videoId?: true
  triggerRunId?: true
  workflowStatus?: true
  progressPercent?: true
  progressLabel?: true
  errorMessage?: true
  createdAt?: true
  updatedAt?: true
}

export type ProductVideoMaxAggregateInputType = {
  id?: true
  productsHash?: true
  videoKey?: true
  videoId?: true
  triggerRunId?: true
  workflowStatus?: true
  progressPercent?: true
  progressLabel?: true
  errorMessage?: true
  createdAt?: true
  updatedAt?: true
}

export type ProductVideoCountAggregateInputType = {
  id?: true
  productsHash?: true
  videoKey?: true
  videoId?: true
  triggerRunId?: true
  workflowStatus?: true
  progressPercent?: true
  progressLabel?: true
  errorMessage?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ProductVideoAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ProductVideo to aggregate.
   */
  where?: Prisma.ProductVideoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProductVideos to fetch.
   */
  orderBy?: Prisma.ProductVideoOrderByWithRelationInput | Prisma.ProductVideoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ProductVideoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProductVideos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProductVideos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ProductVideos
  **/
  _count?: true | ProductVideoCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ProductVideoAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ProductVideoSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ProductVideoMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ProductVideoMaxAggregateInputType
}

export type GetProductVideoAggregateType<T extends ProductVideoAggregateArgs> = {
      [P in keyof T & keyof AggregateProductVideo]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateProductVideo[P]>
    : Prisma.GetScalarType<T[P], AggregateProductVideo[P]>
}




export type ProductVideoGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProductVideoWhereInput
  orderBy?: Prisma.ProductVideoOrderByWithAggregationInput | Prisma.ProductVideoOrderByWithAggregationInput[]
  by: Prisma.ProductVideoScalarFieldEnum[] | Prisma.ProductVideoScalarFieldEnum
  having?: Prisma.ProductVideoScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ProductVideoCountAggregateInputType | true
  _avg?: ProductVideoAvgAggregateInputType
  _sum?: ProductVideoSumAggregateInputType
  _min?: ProductVideoMinAggregateInputType
  _max?: ProductVideoMaxAggregateInputType
}

export type ProductVideoGroupByOutputType = {
  id: string
  productsHash: string
  videoKey: string | null
  videoId: string | null
  triggerRunId: string | null
  workflowStatus: $Enums.ProductVideoWorkflowStatus
  progressPercent: number
  progressLabel: string | null
  errorMessage: string | null
  createdAt: Date
  updatedAt: Date
  _count: ProductVideoCountAggregateOutputType | null
  _avg: ProductVideoAvgAggregateOutputType | null
  _sum: ProductVideoSumAggregateOutputType | null
  _min: ProductVideoMinAggregateOutputType | null
  _max: ProductVideoMaxAggregateOutputType | null
}

export type GetProductVideoGroupByPayload<T extends ProductVideoGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ProductVideoGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ProductVideoGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ProductVideoGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ProductVideoGroupByOutputType[P]>
      }
    >
  >



export type ProductVideoWhereInput = {
  AND?: Prisma.ProductVideoWhereInput | Prisma.ProductVideoWhereInput[]
  OR?: Prisma.ProductVideoWhereInput[]
  NOT?: Prisma.ProductVideoWhereInput | Prisma.ProductVideoWhereInput[]
  id?: Prisma.StringFilter<"ProductVideo"> | string
  productsHash?: Prisma.StringFilter<"ProductVideo"> | string
  videoKey?: Prisma.StringNullableFilter<"ProductVideo"> | string | null
  videoId?: Prisma.StringNullableFilter<"ProductVideo"> | string | null
  triggerRunId?: Prisma.StringNullableFilter<"ProductVideo"> | string | null
  workflowStatus?: Prisma.EnumProductVideoWorkflowStatusFilter<"ProductVideo"> | $Enums.ProductVideoWorkflowStatus
  progressPercent?: Prisma.IntFilter<"ProductVideo"> | number
  progressLabel?: Prisma.StringNullableFilter<"ProductVideo"> | string | null
  errorMessage?: Prisma.StringNullableFilter<"ProductVideo"> | string | null
  createdAt?: Prisma.DateTimeFilter<"ProductVideo"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ProductVideo"> | Date | string
  products?: Prisma.ProductListRelationFilter
}

export type ProductVideoOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  productsHash?: Prisma.SortOrder
  videoKey?: Prisma.SortOrderInput | Prisma.SortOrder
  videoId?: Prisma.SortOrderInput | Prisma.SortOrder
  triggerRunId?: Prisma.SortOrderInput | Prisma.SortOrder
  workflowStatus?: Prisma.SortOrder
  progressPercent?: Prisma.SortOrder
  progressLabel?: Prisma.SortOrderInput | Prisma.SortOrder
  errorMessage?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  products?: Prisma.ProductOrderByRelationAggregateInput
}

export type ProductVideoWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  productsHash?: string
  AND?: Prisma.ProductVideoWhereInput | Prisma.ProductVideoWhereInput[]
  OR?: Prisma.ProductVideoWhereInput[]
  NOT?: Prisma.ProductVideoWhereInput | Prisma.ProductVideoWhereInput[]
  videoKey?: Prisma.StringNullableFilter<"ProductVideo"> | string | null
  videoId?: Prisma.StringNullableFilter<"ProductVideo"> | string | null
  triggerRunId?: Prisma.StringNullableFilter<"ProductVideo"> | string | null
  workflowStatus?: Prisma.EnumProductVideoWorkflowStatusFilter<"ProductVideo"> | $Enums.ProductVideoWorkflowStatus
  progressPercent?: Prisma.IntFilter<"ProductVideo"> | number
  progressLabel?: Prisma.StringNullableFilter<"ProductVideo"> | string | null
  errorMessage?: Prisma.StringNullableFilter<"ProductVideo"> | string | null
  createdAt?: Prisma.DateTimeFilter<"ProductVideo"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ProductVideo"> | Date | string
  products?: Prisma.ProductListRelationFilter
}, "id" | "productsHash">

export type ProductVideoOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  productsHash?: Prisma.SortOrder
  videoKey?: Prisma.SortOrderInput | Prisma.SortOrder
  videoId?: Prisma.SortOrderInput | Prisma.SortOrder
  triggerRunId?: Prisma.SortOrderInput | Prisma.SortOrder
  workflowStatus?: Prisma.SortOrder
  progressPercent?: Prisma.SortOrder
  progressLabel?: Prisma.SortOrderInput | Prisma.SortOrder
  errorMessage?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ProductVideoCountOrderByAggregateInput
  _avg?: Prisma.ProductVideoAvgOrderByAggregateInput
  _max?: Prisma.ProductVideoMaxOrderByAggregateInput
  _min?: Prisma.ProductVideoMinOrderByAggregateInput
  _sum?: Prisma.ProductVideoSumOrderByAggregateInput
}

export type ProductVideoScalarWhereWithAggregatesInput = {
  AND?: Prisma.ProductVideoScalarWhereWithAggregatesInput | Prisma.ProductVideoScalarWhereWithAggregatesInput[]
  OR?: Prisma.ProductVideoScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ProductVideoScalarWhereWithAggregatesInput | Prisma.ProductVideoScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ProductVideo"> | string
  productsHash?: Prisma.StringWithAggregatesFilter<"ProductVideo"> | string
  videoKey?: Prisma.StringNullableWithAggregatesFilter<"ProductVideo"> | string | null
  videoId?: Prisma.StringNullableWithAggregatesFilter<"ProductVideo"> | string | null
  triggerRunId?: Prisma.StringNullableWithAggregatesFilter<"ProductVideo"> | string | null
  workflowStatus?: Prisma.EnumProductVideoWorkflowStatusWithAggregatesFilter<"ProductVideo"> | $Enums.ProductVideoWorkflowStatus
  progressPercent?: Prisma.IntWithAggregatesFilter<"ProductVideo"> | number
  progressLabel?: Prisma.StringNullableWithAggregatesFilter<"ProductVideo"> | string | null
  errorMessage?: Prisma.StringNullableWithAggregatesFilter<"ProductVideo"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ProductVideo"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"ProductVideo"> | Date | string
}

export type ProductVideoCreateInput = {
  id?: string
  productsHash: string
  videoKey?: string | null
  videoId?: string | null
  triggerRunId?: string | null
  workflowStatus?: $Enums.ProductVideoWorkflowStatus
  progressPercent?: number
  progressLabel?: string | null
  errorMessage?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  products?: Prisma.ProductCreateNestedManyWithoutProductVideosInput
}

export type ProductVideoUncheckedCreateInput = {
  id?: string
  productsHash: string
  videoKey?: string | null
  videoId?: string | null
  triggerRunId?: string | null
  workflowStatus?: $Enums.ProductVideoWorkflowStatus
  progressPercent?: number
  progressLabel?: string | null
  errorMessage?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  products?: Prisma.ProductUncheckedCreateNestedManyWithoutProductVideosInput
}

export type ProductVideoUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productsHash?: Prisma.StringFieldUpdateOperationsInput | string
  videoKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  videoId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  triggerRunId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  workflowStatus?: Prisma.EnumProductVideoWorkflowStatusFieldUpdateOperationsInput | $Enums.ProductVideoWorkflowStatus
  progressPercent?: Prisma.IntFieldUpdateOperationsInput | number
  progressLabel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  errorMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  products?: Prisma.ProductUpdateManyWithoutProductVideosNestedInput
}

export type ProductVideoUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productsHash?: Prisma.StringFieldUpdateOperationsInput | string
  videoKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  videoId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  triggerRunId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  workflowStatus?: Prisma.EnumProductVideoWorkflowStatusFieldUpdateOperationsInput | $Enums.ProductVideoWorkflowStatus
  progressPercent?: Prisma.IntFieldUpdateOperationsInput | number
  progressLabel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  errorMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  products?: Prisma.ProductUncheckedUpdateManyWithoutProductVideosNestedInput
}

export type ProductVideoCreateManyInput = {
  id?: string
  productsHash: string
  videoKey?: string | null
  videoId?: string | null
  triggerRunId?: string | null
  workflowStatus?: $Enums.ProductVideoWorkflowStatus
  progressPercent?: number
  progressLabel?: string | null
  errorMessage?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ProductVideoUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productsHash?: Prisma.StringFieldUpdateOperationsInput | string
  videoKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  videoId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  triggerRunId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  workflowStatus?: Prisma.EnumProductVideoWorkflowStatusFieldUpdateOperationsInput | $Enums.ProductVideoWorkflowStatus
  progressPercent?: Prisma.IntFieldUpdateOperationsInput | number
  progressLabel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  errorMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProductVideoUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productsHash?: Prisma.StringFieldUpdateOperationsInput | string
  videoKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  videoId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  triggerRunId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  workflowStatus?: Prisma.EnumProductVideoWorkflowStatusFieldUpdateOperationsInput | $Enums.ProductVideoWorkflowStatus
  progressPercent?: Prisma.IntFieldUpdateOperationsInput | number
  progressLabel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  errorMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProductVideoListRelationFilter = {
  every?: Prisma.ProductVideoWhereInput
  some?: Prisma.ProductVideoWhereInput
  none?: Prisma.ProductVideoWhereInput
}

export type ProductVideoOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ProductVideoCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  productsHash?: Prisma.SortOrder
  videoKey?: Prisma.SortOrder
  videoId?: Prisma.SortOrder
  triggerRunId?: Prisma.SortOrder
  workflowStatus?: Prisma.SortOrder
  progressPercent?: Prisma.SortOrder
  progressLabel?: Prisma.SortOrder
  errorMessage?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ProductVideoAvgOrderByAggregateInput = {
  progressPercent?: Prisma.SortOrder
}

export type ProductVideoMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  productsHash?: Prisma.SortOrder
  videoKey?: Prisma.SortOrder
  videoId?: Prisma.SortOrder
  triggerRunId?: Prisma.SortOrder
  workflowStatus?: Prisma.SortOrder
  progressPercent?: Prisma.SortOrder
  progressLabel?: Prisma.SortOrder
  errorMessage?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ProductVideoMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  productsHash?: Prisma.SortOrder
  videoKey?: Prisma.SortOrder
  videoId?: Prisma.SortOrder
  triggerRunId?: Prisma.SortOrder
  workflowStatus?: Prisma.SortOrder
  progressPercent?: Prisma.SortOrder
  progressLabel?: Prisma.SortOrder
  errorMessage?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ProductVideoSumOrderByAggregateInput = {
  progressPercent?: Prisma.SortOrder
}

export type ProductVideoCreateNestedManyWithoutProductsInput = {
  create?: Prisma.XOR<Prisma.ProductVideoCreateWithoutProductsInput, Prisma.ProductVideoUncheckedCreateWithoutProductsInput> | Prisma.ProductVideoCreateWithoutProductsInput[] | Prisma.ProductVideoUncheckedCreateWithoutProductsInput[]
  connectOrCreate?: Prisma.ProductVideoCreateOrConnectWithoutProductsInput | Prisma.ProductVideoCreateOrConnectWithoutProductsInput[]
  connect?: Prisma.ProductVideoWhereUniqueInput | Prisma.ProductVideoWhereUniqueInput[]
}

export type ProductVideoUncheckedCreateNestedManyWithoutProductsInput = {
  create?: Prisma.XOR<Prisma.ProductVideoCreateWithoutProductsInput, Prisma.ProductVideoUncheckedCreateWithoutProductsInput> | Prisma.ProductVideoCreateWithoutProductsInput[] | Prisma.ProductVideoUncheckedCreateWithoutProductsInput[]
  connectOrCreate?: Prisma.ProductVideoCreateOrConnectWithoutProductsInput | Prisma.ProductVideoCreateOrConnectWithoutProductsInput[]
  connect?: Prisma.ProductVideoWhereUniqueInput | Prisma.ProductVideoWhereUniqueInput[]
}

export type ProductVideoUpdateManyWithoutProductsNestedInput = {
  create?: Prisma.XOR<Prisma.ProductVideoCreateWithoutProductsInput, Prisma.ProductVideoUncheckedCreateWithoutProductsInput> | Prisma.ProductVideoCreateWithoutProductsInput[] | Prisma.ProductVideoUncheckedCreateWithoutProductsInput[]
  connectOrCreate?: Prisma.ProductVideoCreateOrConnectWithoutProductsInput | Prisma.ProductVideoCreateOrConnectWithoutProductsInput[]
  upsert?: Prisma.ProductVideoUpsertWithWhereUniqueWithoutProductsInput | Prisma.ProductVideoUpsertWithWhereUniqueWithoutProductsInput[]
  set?: Prisma.ProductVideoWhereUniqueInput | Prisma.ProductVideoWhereUniqueInput[]
  disconnect?: Prisma.ProductVideoWhereUniqueInput | Prisma.ProductVideoWhereUniqueInput[]
  delete?: Prisma.ProductVideoWhereUniqueInput | Prisma.ProductVideoWhereUniqueInput[]
  connect?: Prisma.ProductVideoWhereUniqueInput | Prisma.ProductVideoWhereUniqueInput[]
  update?: Prisma.ProductVideoUpdateWithWhereUniqueWithoutProductsInput | Prisma.ProductVideoUpdateWithWhereUniqueWithoutProductsInput[]
  updateMany?: Prisma.ProductVideoUpdateManyWithWhereWithoutProductsInput | Prisma.ProductVideoUpdateManyWithWhereWithoutProductsInput[]
  deleteMany?: Prisma.ProductVideoScalarWhereInput | Prisma.ProductVideoScalarWhereInput[]
}

export type ProductVideoUncheckedUpdateManyWithoutProductsNestedInput = {
  create?: Prisma.XOR<Prisma.ProductVideoCreateWithoutProductsInput, Prisma.ProductVideoUncheckedCreateWithoutProductsInput> | Prisma.ProductVideoCreateWithoutProductsInput[] | Prisma.ProductVideoUncheckedCreateWithoutProductsInput[]
  connectOrCreate?: Prisma.ProductVideoCreateOrConnectWithoutProductsInput | Prisma.ProductVideoCreateOrConnectWithoutProductsInput[]
  upsert?: Prisma.ProductVideoUpsertWithWhereUniqueWithoutProductsInput | Prisma.ProductVideoUpsertWithWhereUniqueWithoutProductsInput[]
  set?: Prisma.ProductVideoWhereUniqueInput | Prisma.ProductVideoWhereUniqueInput[]
  disconnect?: Prisma.ProductVideoWhereUniqueInput | Prisma.ProductVideoWhereUniqueInput[]
  delete?: Prisma.ProductVideoWhereUniqueInput | Prisma.ProductVideoWhereUniqueInput[]
  connect?: Prisma.ProductVideoWhereUniqueInput | Prisma.ProductVideoWhereUniqueInput[]
  update?: Prisma.ProductVideoUpdateWithWhereUniqueWithoutProductsInput | Prisma.ProductVideoUpdateWithWhereUniqueWithoutProductsInput[]
  updateMany?: Prisma.ProductVideoUpdateManyWithWhereWithoutProductsInput | Prisma.ProductVideoUpdateManyWithWhereWithoutProductsInput[]
  deleteMany?: Prisma.ProductVideoScalarWhereInput | Prisma.ProductVideoScalarWhereInput[]
}

export type EnumProductVideoWorkflowStatusFieldUpdateOperationsInput = {
  set?: $Enums.ProductVideoWorkflowStatus
}

export type ProductVideoCreateWithoutProductsInput = {
  id?: string
  productsHash: string
  videoKey?: string | null
  videoId?: string | null
  triggerRunId?: string | null
  workflowStatus?: $Enums.ProductVideoWorkflowStatus
  progressPercent?: number
  progressLabel?: string | null
  errorMessage?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ProductVideoUncheckedCreateWithoutProductsInput = {
  id?: string
  productsHash: string
  videoKey?: string | null
  videoId?: string | null
  triggerRunId?: string | null
  workflowStatus?: $Enums.ProductVideoWorkflowStatus
  progressPercent?: number
  progressLabel?: string | null
  errorMessage?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ProductVideoCreateOrConnectWithoutProductsInput = {
  where: Prisma.ProductVideoWhereUniqueInput
  create: Prisma.XOR<Prisma.ProductVideoCreateWithoutProductsInput, Prisma.ProductVideoUncheckedCreateWithoutProductsInput>
}

export type ProductVideoUpsertWithWhereUniqueWithoutProductsInput = {
  where: Prisma.ProductVideoWhereUniqueInput
  update: Prisma.XOR<Prisma.ProductVideoUpdateWithoutProductsInput, Prisma.ProductVideoUncheckedUpdateWithoutProductsInput>
  create: Prisma.XOR<Prisma.ProductVideoCreateWithoutProductsInput, Prisma.ProductVideoUncheckedCreateWithoutProductsInput>
}

export type ProductVideoUpdateWithWhereUniqueWithoutProductsInput = {
  where: Prisma.ProductVideoWhereUniqueInput
  data: Prisma.XOR<Prisma.ProductVideoUpdateWithoutProductsInput, Prisma.ProductVideoUncheckedUpdateWithoutProductsInput>
}

export type ProductVideoUpdateManyWithWhereWithoutProductsInput = {
  where: Prisma.ProductVideoScalarWhereInput
  data: Prisma.XOR<Prisma.ProductVideoUpdateManyMutationInput, Prisma.ProductVideoUncheckedUpdateManyWithoutProductsInput>
}

export type ProductVideoScalarWhereInput = {
  AND?: Prisma.ProductVideoScalarWhereInput | Prisma.ProductVideoScalarWhereInput[]
  OR?: Prisma.ProductVideoScalarWhereInput[]
  NOT?: Prisma.ProductVideoScalarWhereInput | Prisma.ProductVideoScalarWhereInput[]
  id?: Prisma.StringFilter<"ProductVideo"> | string
  productsHash?: Prisma.StringFilter<"ProductVideo"> | string
  videoKey?: Prisma.StringNullableFilter<"ProductVideo"> | string | null
  videoId?: Prisma.StringNullableFilter<"ProductVideo"> | string | null
  triggerRunId?: Prisma.StringNullableFilter<"ProductVideo"> | string | null
  workflowStatus?: Prisma.EnumProductVideoWorkflowStatusFilter<"ProductVideo"> | $Enums.ProductVideoWorkflowStatus
  progressPercent?: Prisma.IntFilter<"ProductVideo"> | number
  progressLabel?: Prisma.StringNullableFilter<"ProductVideo"> | string | null
  errorMessage?: Prisma.StringNullableFilter<"ProductVideo"> | string | null
  createdAt?: Prisma.DateTimeFilter<"ProductVideo"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ProductVideo"> | Date | string
}

export type ProductVideoUpdateWithoutProductsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productsHash?: Prisma.StringFieldUpdateOperationsInput | string
  videoKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  videoId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  triggerRunId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  workflowStatus?: Prisma.EnumProductVideoWorkflowStatusFieldUpdateOperationsInput | $Enums.ProductVideoWorkflowStatus
  progressPercent?: Prisma.IntFieldUpdateOperationsInput | number
  progressLabel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  errorMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProductVideoUncheckedUpdateWithoutProductsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productsHash?: Prisma.StringFieldUpdateOperationsInput | string
  videoKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  videoId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  triggerRunId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  workflowStatus?: Prisma.EnumProductVideoWorkflowStatusFieldUpdateOperationsInput | $Enums.ProductVideoWorkflowStatus
  progressPercent?: Prisma.IntFieldUpdateOperationsInput | number
  progressLabel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  errorMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProductVideoUncheckedUpdateManyWithoutProductsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  productsHash?: Prisma.StringFieldUpdateOperationsInput | string
  videoKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  videoId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  triggerRunId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  workflowStatus?: Prisma.EnumProductVideoWorkflowStatusFieldUpdateOperationsInput | $Enums.ProductVideoWorkflowStatus
  progressPercent?: Prisma.IntFieldUpdateOperationsInput | number
  progressLabel?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  errorMessage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type ProductVideoCountOutputType
 */

export type ProductVideoCountOutputType = {
  products: number
}

export type ProductVideoCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  products?: boolean | ProductVideoCountOutputTypeCountProductsArgs
}

/**
 * ProductVideoCountOutputType without action
 */
export type ProductVideoCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductVideoCountOutputType
   */
  select?: Prisma.ProductVideoCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ProductVideoCountOutputType without action
 */
export type ProductVideoCountOutputTypeCountProductsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProductWhereInput
}


export type ProductVideoSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  productsHash?: boolean
  videoKey?: boolean
  videoId?: boolean
  triggerRunId?: boolean
  workflowStatus?: boolean
  progressPercent?: boolean
  progressLabel?: boolean
  errorMessage?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  products?: boolean | Prisma.ProductVideo$productsArgs<ExtArgs>
  _count?: boolean | Prisma.ProductVideoCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["productVideo"]>

export type ProductVideoSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  productsHash?: boolean
  videoKey?: boolean
  videoId?: boolean
  triggerRunId?: boolean
  workflowStatus?: boolean
  progressPercent?: boolean
  progressLabel?: boolean
  errorMessage?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["productVideo"]>

export type ProductVideoSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  productsHash?: boolean
  videoKey?: boolean
  videoId?: boolean
  triggerRunId?: boolean
  workflowStatus?: boolean
  progressPercent?: boolean
  progressLabel?: boolean
  errorMessage?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["productVideo"]>

export type ProductVideoSelectScalar = {
  id?: boolean
  productsHash?: boolean
  videoKey?: boolean
  videoId?: boolean
  triggerRunId?: boolean
  workflowStatus?: boolean
  progressPercent?: boolean
  progressLabel?: boolean
  errorMessage?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ProductVideoOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "productsHash" | "videoKey" | "videoId" | "triggerRunId" | "workflowStatus" | "progressPercent" | "progressLabel" | "errorMessage" | "createdAt" | "updatedAt", ExtArgs["result"]["productVideo"]>
export type ProductVideoInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  products?: boolean | Prisma.ProductVideo$productsArgs<ExtArgs>
  _count?: boolean | Prisma.ProductVideoCountOutputTypeDefaultArgs<ExtArgs>
}
export type ProductVideoIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type ProductVideoIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $ProductVideoPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ProductVideo"
  objects: {
    products: Prisma.$ProductPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    productsHash: string
    videoKey: string | null
    videoId: string | null
    triggerRunId: string | null
    workflowStatus: $Enums.ProductVideoWorkflowStatus
    progressPercent: number
    progressLabel: string | null
    errorMessage: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["productVideo"]>
  composites: {}
}

export type ProductVideoGetPayload<S extends boolean | null | undefined | ProductVideoDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ProductVideoPayload, S>

export type ProductVideoCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ProductVideoFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ProductVideoCountAggregateInputType | true
  }

export interface ProductVideoDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ProductVideo'], meta: { name: 'ProductVideo' } }
  /**
   * Find zero or one ProductVideo that matches the filter.
   * @param {ProductVideoFindUniqueArgs} args - Arguments to find a ProductVideo
   * @example
   * // Get one ProductVideo
   * const productVideo = await prisma.productVideo.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ProductVideoFindUniqueArgs>(args: Prisma.SelectSubset<T, ProductVideoFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ProductVideoClient<runtime.Types.Result.GetResult<Prisma.$ProductVideoPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ProductVideo that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ProductVideoFindUniqueOrThrowArgs} args - Arguments to find a ProductVideo
   * @example
   * // Get one ProductVideo
   * const productVideo = await prisma.productVideo.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ProductVideoFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ProductVideoFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProductVideoClient<runtime.Types.Result.GetResult<Prisma.$ProductVideoPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ProductVideo that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductVideoFindFirstArgs} args - Arguments to find a ProductVideo
   * @example
   * // Get one ProductVideo
   * const productVideo = await prisma.productVideo.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ProductVideoFindFirstArgs>(args?: Prisma.SelectSubset<T, ProductVideoFindFirstArgs<ExtArgs>>): Prisma.Prisma__ProductVideoClient<runtime.Types.Result.GetResult<Prisma.$ProductVideoPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ProductVideo that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductVideoFindFirstOrThrowArgs} args - Arguments to find a ProductVideo
   * @example
   * // Get one ProductVideo
   * const productVideo = await prisma.productVideo.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ProductVideoFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ProductVideoFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProductVideoClient<runtime.Types.Result.GetResult<Prisma.$ProductVideoPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ProductVideos that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductVideoFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ProductVideos
   * const productVideos = await prisma.productVideo.findMany()
   * 
   * // Get first 10 ProductVideos
   * const productVideos = await prisma.productVideo.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const productVideoWithIdOnly = await prisma.productVideo.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ProductVideoFindManyArgs>(args?: Prisma.SelectSubset<T, ProductVideoFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProductVideoPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ProductVideo.
   * @param {ProductVideoCreateArgs} args - Arguments to create a ProductVideo.
   * @example
   * // Create one ProductVideo
   * const ProductVideo = await prisma.productVideo.create({
   *   data: {
   *     // ... data to create a ProductVideo
   *   }
   * })
   * 
   */
  create<T extends ProductVideoCreateArgs>(args: Prisma.SelectSubset<T, ProductVideoCreateArgs<ExtArgs>>): Prisma.Prisma__ProductVideoClient<runtime.Types.Result.GetResult<Prisma.$ProductVideoPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ProductVideos.
   * @param {ProductVideoCreateManyArgs} args - Arguments to create many ProductVideos.
   * @example
   * // Create many ProductVideos
   * const productVideo = await prisma.productVideo.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ProductVideoCreateManyArgs>(args?: Prisma.SelectSubset<T, ProductVideoCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ProductVideos and returns the data saved in the database.
   * @param {ProductVideoCreateManyAndReturnArgs} args - Arguments to create many ProductVideos.
   * @example
   * // Create many ProductVideos
   * const productVideo = await prisma.productVideo.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ProductVideos and only return the `id`
   * const productVideoWithIdOnly = await prisma.productVideo.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ProductVideoCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ProductVideoCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProductVideoPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ProductVideo.
   * @param {ProductVideoDeleteArgs} args - Arguments to delete one ProductVideo.
   * @example
   * // Delete one ProductVideo
   * const ProductVideo = await prisma.productVideo.delete({
   *   where: {
   *     // ... filter to delete one ProductVideo
   *   }
   * })
   * 
   */
  delete<T extends ProductVideoDeleteArgs>(args: Prisma.SelectSubset<T, ProductVideoDeleteArgs<ExtArgs>>): Prisma.Prisma__ProductVideoClient<runtime.Types.Result.GetResult<Prisma.$ProductVideoPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ProductVideo.
   * @param {ProductVideoUpdateArgs} args - Arguments to update one ProductVideo.
   * @example
   * // Update one ProductVideo
   * const productVideo = await prisma.productVideo.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ProductVideoUpdateArgs>(args: Prisma.SelectSubset<T, ProductVideoUpdateArgs<ExtArgs>>): Prisma.Prisma__ProductVideoClient<runtime.Types.Result.GetResult<Prisma.$ProductVideoPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ProductVideos.
   * @param {ProductVideoDeleteManyArgs} args - Arguments to filter ProductVideos to delete.
   * @example
   * // Delete a few ProductVideos
   * const { count } = await prisma.productVideo.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ProductVideoDeleteManyArgs>(args?: Prisma.SelectSubset<T, ProductVideoDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ProductVideos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductVideoUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ProductVideos
   * const productVideo = await prisma.productVideo.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ProductVideoUpdateManyArgs>(args: Prisma.SelectSubset<T, ProductVideoUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ProductVideos and returns the data updated in the database.
   * @param {ProductVideoUpdateManyAndReturnArgs} args - Arguments to update many ProductVideos.
   * @example
   * // Update many ProductVideos
   * const productVideo = await prisma.productVideo.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ProductVideos and only return the `id`
   * const productVideoWithIdOnly = await prisma.productVideo.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ProductVideoUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ProductVideoUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProductVideoPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ProductVideo.
   * @param {ProductVideoUpsertArgs} args - Arguments to update or create a ProductVideo.
   * @example
   * // Update or create a ProductVideo
   * const productVideo = await prisma.productVideo.upsert({
   *   create: {
   *     // ... data to create a ProductVideo
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ProductVideo we want to update
   *   }
   * })
   */
  upsert<T extends ProductVideoUpsertArgs>(args: Prisma.SelectSubset<T, ProductVideoUpsertArgs<ExtArgs>>): Prisma.Prisma__ProductVideoClient<runtime.Types.Result.GetResult<Prisma.$ProductVideoPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ProductVideos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductVideoCountArgs} args - Arguments to filter ProductVideos to count.
   * @example
   * // Count the number of ProductVideos
   * const count = await prisma.productVideo.count({
   *   where: {
   *     // ... the filter for the ProductVideos we want to count
   *   }
   * })
  **/
  count<T extends ProductVideoCountArgs>(
    args?: Prisma.Subset<T, ProductVideoCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ProductVideoCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ProductVideo.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductVideoAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ProductVideoAggregateArgs>(args: Prisma.Subset<T, ProductVideoAggregateArgs>): Prisma.PrismaPromise<GetProductVideoAggregateType<T>>

  /**
   * Group by ProductVideo.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProductVideoGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ProductVideoGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ProductVideoGroupByArgs['orderBy'] }
      : { orderBy?: ProductVideoGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ProductVideoGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetProductVideoGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ProductVideo model
 */
readonly fields: ProductVideoFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ProductVideo.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ProductVideoClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  products<T extends Prisma.ProductVideo$productsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProductVideo$productsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProductPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ProductVideo model
 */
export interface ProductVideoFieldRefs {
  readonly id: Prisma.FieldRef<"ProductVideo", 'String'>
  readonly productsHash: Prisma.FieldRef<"ProductVideo", 'String'>
  readonly videoKey: Prisma.FieldRef<"ProductVideo", 'String'>
  readonly videoId: Prisma.FieldRef<"ProductVideo", 'String'>
  readonly triggerRunId: Prisma.FieldRef<"ProductVideo", 'String'>
  readonly workflowStatus: Prisma.FieldRef<"ProductVideo", 'ProductVideoWorkflowStatus'>
  readonly progressPercent: Prisma.FieldRef<"ProductVideo", 'Int'>
  readonly progressLabel: Prisma.FieldRef<"ProductVideo", 'String'>
  readonly errorMessage: Prisma.FieldRef<"ProductVideo", 'String'>
  readonly createdAt: Prisma.FieldRef<"ProductVideo", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"ProductVideo", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ProductVideo findUnique
 */
export type ProductVideoFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductVideo
   */
  select?: Prisma.ProductVideoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductVideo
   */
  omit?: Prisma.ProductVideoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductVideoInclude<ExtArgs> | null
  /**
   * Filter, which ProductVideo to fetch.
   */
  where: Prisma.ProductVideoWhereUniqueInput
}

/**
 * ProductVideo findUniqueOrThrow
 */
export type ProductVideoFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductVideo
   */
  select?: Prisma.ProductVideoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductVideo
   */
  omit?: Prisma.ProductVideoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductVideoInclude<ExtArgs> | null
  /**
   * Filter, which ProductVideo to fetch.
   */
  where: Prisma.ProductVideoWhereUniqueInput
}

/**
 * ProductVideo findFirst
 */
export type ProductVideoFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductVideo
   */
  select?: Prisma.ProductVideoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductVideo
   */
  omit?: Prisma.ProductVideoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductVideoInclude<ExtArgs> | null
  /**
   * Filter, which ProductVideo to fetch.
   */
  where?: Prisma.ProductVideoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProductVideos to fetch.
   */
  orderBy?: Prisma.ProductVideoOrderByWithRelationInput | Prisma.ProductVideoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ProductVideos.
   */
  cursor?: Prisma.ProductVideoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProductVideos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProductVideos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProductVideos.
   */
  distinct?: Prisma.ProductVideoScalarFieldEnum | Prisma.ProductVideoScalarFieldEnum[]
}

/**
 * ProductVideo findFirstOrThrow
 */
export type ProductVideoFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductVideo
   */
  select?: Prisma.ProductVideoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductVideo
   */
  omit?: Prisma.ProductVideoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductVideoInclude<ExtArgs> | null
  /**
   * Filter, which ProductVideo to fetch.
   */
  where?: Prisma.ProductVideoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProductVideos to fetch.
   */
  orderBy?: Prisma.ProductVideoOrderByWithRelationInput | Prisma.ProductVideoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ProductVideos.
   */
  cursor?: Prisma.ProductVideoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProductVideos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProductVideos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProductVideos.
   */
  distinct?: Prisma.ProductVideoScalarFieldEnum | Prisma.ProductVideoScalarFieldEnum[]
}

/**
 * ProductVideo findMany
 */
export type ProductVideoFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductVideo
   */
  select?: Prisma.ProductVideoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductVideo
   */
  omit?: Prisma.ProductVideoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductVideoInclude<ExtArgs> | null
  /**
   * Filter, which ProductVideos to fetch.
   */
  where?: Prisma.ProductVideoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ProductVideos to fetch.
   */
  orderBy?: Prisma.ProductVideoOrderByWithRelationInput | Prisma.ProductVideoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ProductVideos.
   */
  cursor?: Prisma.ProductVideoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ProductVideos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ProductVideos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ProductVideos.
   */
  distinct?: Prisma.ProductVideoScalarFieldEnum | Prisma.ProductVideoScalarFieldEnum[]
}

/**
 * ProductVideo create
 */
export type ProductVideoCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductVideo
   */
  select?: Prisma.ProductVideoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductVideo
   */
  omit?: Prisma.ProductVideoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductVideoInclude<ExtArgs> | null
  /**
   * The data needed to create a ProductVideo.
   */
  data: Prisma.XOR<Prisma.ProductVideoCreateInput, Prisma.ProductVideoUncheckedCreateInput>
}

/**
 * ProductVideo createMany
 */
export type ProductVideoCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ProductVideos.
   */
  data: Prisma.ProductVideoCreateManyInput | Prisma.ProductVideoCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ProductVideo createManyAndReturn
 */
export type ProductVideoCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductVideo
   */
  select?: Prisma.ProductVideoSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ProductVideo
   */
  omit?: Prisma.ProductVideoOmit<ExtArgs> | null
  /**
   * The data used to create many ProductVideos.
   */
  data: Prisma.ProductVideoCreateManyInput | Prisma.ProductVideoCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ProductVideo update
 */
export type ProductVideoUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductVideo
   */
  select?: Prisma.ProductVideoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductVideo
   */
  omit?: Prisma.ProductVideoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductVideoInclude<ExtArgs> | null
  /**
   * The data needed to update a ProductVideo.
   */
  data: Prisma.XOR<Prisma.ProductVideoUpdateInput, Prisma.ProductVideoUncheckedUpdateInput>
  /**
   * Choose, which ProductVideo to update.
   */
  where: Prisma.ProductVideoWhereUniqueInput
}

/**
 * ProductVideo updateMany
 */
export type ProductVideoUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ProductVideos.
   */
  data: Prisma.XOR<Prisma.ProductVideoUpdateManyMutationInput, Prisma.ProductVideoUncheckedUpdateManyInput>
  /**
   * Filter which ProductVideos to update
   */
  where?: Prisma.ProductVideoWhereInput
  /**
   * Limit how many ProductVideos to update.
   */
  limit?: number
}

/**
 * ProductVideo updateManyAndReturn
 */
export type ProductVideoUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductVideo
   */
  select?: Prisma.ProductVideoSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ProductVideo
   */
  omit?: Prisma.ProductVideoOmit<ExtArgs> | null
  /**
   * The data used to update ProductVideos.
   */
  data: Prisma.XOR<Prisma.ProductVideoUpdateManyMutationInput, Prisma.ProductVideoUncheckedUpdateManyInput>
  /**
   * Filter which ProductVideos to update
   */
  where?: Prisma.ProductVideoWhereInput
  /**
   * Limit how many ProductVideos to update.
   */
  limit?: number
}

/**
 * ProductVideo upsert
 */
export type ProductVideoUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductVideo
   */
  select?: Prisma.ProductVideoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductVideo
   */
  omit?: Prisma.ProductVideoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductVideoInclude<ExtArgs> | null
  /**
   * The filter to search for the ProductVideo to update in case it exists.
   */
  where: Prisma.ProductVideoWhereUniqueInput
  /**
   * In case the ProductVideo found by the `where` argument doesn't exist, create a new ProductVideo with this data.
   */
  create: Prisma.XOR<Prisma.ProductVideoCreateInput, Prisma.ProductVideoUncheckedCreateInput>
  /**
   * In case the ProductVideo was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ProductVideoUpdateInput, Prisma.ProductVideoUncheckedUpdateInput>
}

/**
 * ProductVideo delete
 */
export type ProductVideoDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductVideo
   */
  select?: Prisma.ProductVideoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductVideo
   */
  omit?: Prisma.ProductVideoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductVideoInclude<ExtArgs> | null
  /**
   * Filter which ProductVideo to delete.
   */
  where: Prisma.ProductVideoWhereUniqueInput
}

/**
 * ProductVideo deleteMany
 */
export type ProductVideoDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ProductVideos to delete
   */
  where?: Prisma.ProductVideoWhereInput
  /**
   * Limit how many ProductVideos to delete.
   */
  limit?: number
}

/**
 * ProductVideo.products
 */
export type ProductVideo$productsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Product
   */
  select?: Prisma.ProductSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Product
   */
  omit?: Prisma.ProductOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductInclude<ExtArgs> | null
  where?: Prisma.ProductWhereInput
  orderBy?: Prisma.ProductOrderByWithRelationInput | Prisma.ProductOrderByWithRelationInput[]
  cursor?: Prisma.ProductWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ProductScalarFieldEnum | Prisma.ProductScalarFieldEnum[]
}

/**
 * ProductVideo without action
 */
export type ProductVideoDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductVideo
   */
  select?: Prisma.ProductVideoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductVideo
   */
  omit?: Prisma.ProductVideoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductVideoInclude<ExtArgs> | null
}
