services:
  postgres:
    image: postgres:16-alpine
    container_name: luxora-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: posrgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgre_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

volumes:
  postgre_data:
