
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const ProductType = {
  TOP: 'TOP',
  BOTTOM: 'BOTTOM',
  HEADWEAR: 'HEADWEAR'
} as const

export type ProductType = (typeof ProductType)[keyof typeof ProductType]


export const ProductVideoWorkflowStatus = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED'
} as const

export type ProductVideoWorkflowStatus = (typeof ProductVideoWorkflowStatus)[keyof typeof ProductVideoWorkflowStatus]
